#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: my-db
    image: romainkatzz/tp-devops-database
    networks: 
      - name: my_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
    